# Generated by Django 3.2.9 on 2021-11-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('instagram_link', models.CharField(blank=True, max_length=400)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('date', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
